import { Module } from "./types";

const config: Module[] = [
  {
    id: "_550937_1",
    course: "COMP",
    title: "Computer Architecture",
    module_code: "COMP1211",
    semester: 1,
    year: 1,
    url: "https://minerva.leeds.ac.uk/ultra/courses/_550937_1/outline",
  },
  {
    id: "_550939_1",
    course: "COMP",
    title: "Fundamental Mathematical Concepts",
    module_code: "COMP1421",
    semester: 1,
    year: 1,
    url: "https://minerva.leeds.ac.uk/ultra/courses/_550939_1/outline",
  },
  {
    id: "_550941_1",
    course: "COMP",
    title: "Procedural Programming",
    module_code: "COMP1711",
    semester: 1,
    year: 1,
    url: "https://minerva.leeds.ac.uk/ultra/courses/_550941_1/outline",
  },
  {
    id: "_550943_1",
    course: "COMP",
    title: "Professional Computing",
    module_code: "COMP1911",
    semester: 1,
    year: 1,
    url: "https://minerva.leeds.ac.uk/ultra/courses/_550943_1/outline",
  },
  {
    id: "_548972_1",
    course: "PSYC",
    title: "Introduction to Psychology",
    module_code: "PSYC1601",
    semester: 1,
    year: 1,
    url: "https://minerva.leeds.ac.uk/ultra/courses/_548972_1/outline",
  },
  {
    id: "_550935_1",
    course: "COMP",
    title: "Introduction to Web Technologies",
    module_code: "COMP1021",
    semester: 2,
    year: 1,
    url: "https://minerva.leeds.ac.uk/ultra/courses/_550935_1/outline",
  },
  {
    id: "_550936_1",
    course: "COMP",
    title: "Databases",
    module_code: "COMP1121",
    semester: 2,
    year: 1,
    url: "https://minerva.leeds.ac.uk/ultra/courses/_550936_1/outline",
  },
  {
    id: "_550938_1",
    course: "COMP",
    title: "Computer Processors",
    module_code: "COMP1212",
    semester: 2,
    year: 1,
    url: "https://minerva.leeds.ac.uk/ultra/courses/_550938_1/outline",
  },
  {
    id: "_550940_1",
    course: "COMP",
    title: "Introduction to Discrete Mathematics",
    module_code: "COMP1511",
    semester: 2,
    year: 1,
    url: "https://minerva.leeds.ac.uk/ultra/courses/_550940_1/outline",
  },
  {
    id: "_550942_1",
    course: "COMP",
    title: "Object Oriented Programming",
    module_code: "COMP1721",
    semester: 2,
    year: 1,
    url: "https://minerva.leeds.ac.uk/ultra/courses/_550942_1/outline",
  },
  {
    id: "_550944_1",
    course: "COMP",
    title: "Programming Project",
    module_code: "COMP1921",
    semester: 2,
    year: 1,
    url: "https://minerva.leeds.ac.uk/ultra/courses/_550944_1/outline",
  },
];
export default config;
